<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('categories')->insert(
            [
                [
                'name'=>'Bakery',
                'categoryImage'=>'category-1.png',
                'position'=>'1',
                'is_active'=>'1'
                ],
                [
                'name'=>'Barbecue',
                'categoryImage'=>'category-2.png',
                'position'=>'2',
                'is_active'=>'1'
                ],
                [
                'name'=>'Beverages',
                'categoryImage'=>'category-3.png',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Biryani',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Burgers',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Chaat',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Combo',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Grill',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Ice Cream',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Juices',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Kebabs',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Paan',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],   
                [
                'name'=>'Pastas',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Pizzas',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Salads',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Sweets',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Tandoor',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Thalis',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Waffle',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Desserts',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Cakes',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Street Food',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Sushi',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Seafood',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Snacks',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Shakes',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Pure veg',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Dosa',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'vada',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Idli',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Khichdi',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Tea',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Coffee',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Chicken',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Mutton',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Egg',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Rolls',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Noodles',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Rice',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Pancakes',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Sandwich',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Wraps',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Momos',
                'categoryImage'=>'category-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ]
            ]
            
        
        );
    
    }
}
