<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ContantManagement extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('content_management')->insert(
            [
                [
                'user_privacy_policy'=>'This Privacy Policy applies to the Cheflab
                Cheflab recognizes the importance of maintaining your privacy. We value your privacy and appreciate your trust in us and therefore we are committed to protect the same through this Privacy Policy. This Privacy Policy (“Policy”) describes the policies and procedures on the collection, use, disclosure and protection of your information when you use our website located at cheflab.in, or the Cheflab mobile application (collectively, “Cheflab Platform”) made available by Chotu18 Services Private Limited (“Cheflab”, “Company”, “we”, “us” and “our”),  a private limited company established under the laws of India .
                
                This Privacy Policy applies to current and former visitors to our website and to our online customers. By visiting and/or using our website, you agree to this Privacy Policy. 
                
                Please read this Policy before using the Cheflab Platform or submitting any personal information to Cheflab. This Policy is a part of and incorporated within, and is to be read along with, the Terms of Use. Please read this policy carefully to understand Cheflab’s policies and practices regarding your information and how Cheflab will treat it. By accessing or using its Services and/or registering for an account with Cheflab, you agree to this privacy policy and you are consenting to Cheflab s collection, use and disclosure.
                
                Cheflab is a property of Chotu18 Services Pvt. Ltd, an Indian Company registered under the Companies Act, 2013.
                
                The terms “you” and “your” refer to the user of the Cheflab Platform. The term “Services” refers to any services offered by Cheflab whether on the Cheflab Platform or otherwise.
                
                •	.
                This policy applies only to the information Cheflab collects through its Services, in email, text and other electronic communications sent through or in connection with its Services.
                Chotu18 Services Private Limited,  will be the controller of your personal data provided to, or collected by or for, or processed in connection with our Services.
                Your data controller is responsible for the collection, use, disclosure, retention, and protection of your personal information in accordance with its privacy standards as well as any applicable national laws. Your data controller may transfer data to other members of Cheflab as described in this Privacy Policy. Cheflab may process and retain your personal information on its servers in India where its data centers are located, and/or on the servers of its third parties (in or outside India), having contractual relationships with Cheflab.
                This policy may change from time to time, your continued use of Chefla s Services after it makes any change is deemed to be acceptance of those changes, so please check the policy periodically for updates.
                1. INFORMATION WE COLLECT
                Chotu18 Services Private Limited ("Cheflab," the "Company," "we," "us," and "our”) collects several types of information from and about users of our Services, including
                1.1. Personal Information provided directly by you
                Contact and profile information. When you create an Account, complete your Account profile, sign up for a mailing list, or otherwise communicate or interact with us (whether or not through an Account), we may collect information from you, such as your name, phone number, e-mail address,gender , profile picture and physical address. You may optionally provide us with this information through third-party sign-in services such as Facebook and Google . In such cases, we fetch and store whatever information is made available to us by you through these sign-in services. We use this contact and profile information to: (i) create and personalize your Account; (ii) communicate with you directly about the Services as well as answer any questions, issues or concerns you or other users may have, (iii) fulfill your order, and (iv) send you marketing communications in accordance with your preferences.
                Payment information. When you submit an order ,you are required to provide payment information, such as your credit card, debit card or gift card details. For corporate Accounts that are used for business purposes, we may also have corporate credit card numbers or other payment account numbers. We use this payment information to fulfill your order, complete the transaction, and detect and prevent fraud.
                Transaction information. When you submit an order, we collect information, including the items purchased, the date and time of your transaction, any special instructions, and any points you accrue or rewards or promotions you redeem as part of a loyalty or rewards program. We use this transaction information to fulfill your order, update your rewards, detect and prevent fraud, personalize your experience, perform analytics/identify usage trends, and inform our advertising and marketing.
                Your preferences: Your preferences and settings such as time zone and language.
                Your content: Information you provide through our Services, including your reviews, photographs, comments, lists, followers, the users you follow, current and prior restaurant reservation details, food ordering details and history, favorite restaurants, special restaurant requests, contact information of people you add to, or notify of, your restaurant reservations through our Services, names, and other information you provide on our Services, and other information in your account profile.
                Your searches and other activities: The search terms you have looked up and results you selected.
                Your browsing information: How long you used our Services and which features you used; the ads you clicked on.
                Communications, Participation and other content. We maintain all communications (including email, phone, mail and chat) resulting from your interactions with us or with Delivery Partners. We also record comments and opinions you express when responding to surveys, entering a sweepstakes or taking part in promotions we run. We use all of the foregoing communications to address your questions, issues and concerns and provide other related customer support services, for safety and security purposes, to improve our Services, and for analytics. We also maintain your Ratings and Reviews regarding Chefs/Restaurants on the Platform and/or Services, which we may post for the benefit of all of our users.
                Your transactional information: If you make reservations or purchases through our Services, we may collect and store information about you to process your requests and automatically complete forms for future transactions, including (but not limited to) your phone number, address, email, billing information and credit or payment card information. This information may be shared with third-parties which assist in processing and fulfilling your requests, including PCI compliant payment gateway processors. When you submit credit or payment card information, we encrypt the information using industry standard technologies, as further described below under "Payment Card Information." If you write reviews about businesses with which you conduct transactions through our Services, we may publicly display information that you transacted with those businesses.
                Your Public Posts: You also may provide information (such as ratings, reviews, tips, photos, comments, likes, bookmarks, friends, lists, etc.) to be published or displayed (hereinafter, "posted") on publicly accessible areas of our Services, or transmitted to other users of our Services or third-parties (collectively, "User Contributions"). Your User Contributions are posted on and transmitted to others at your own risk. Although we limit access to certain pages, you may set certain privacy settings for such information by logging into your account profile. Please be aware that no security measures are perfect or impenetrable (see "Security" section below). Additionally, we cannot control the actions of other users of our Services with whom you may choose to share your User Contributions. Therefore, we cannot and do not guarantee that your User Contributions will not be viewed by unauthorized persons. We may display this information on the Services, share it with businesses, and further distribute it to a wider audience through third party sites and services. You should be careful about revealing any sensitive details about yourself in such postings.
                Device Information: In order to improve your app experience and lend stability to our services to you, we may collect information or employ third party plugins that collect information about the devices you use to access our Services, including the hardware models, operating systems and versions, software, file names and versions, preferred languages, unique device identifiers, advertising identifiers, serial numbers, device motion information, mobile network information, installed applications on device and phone state. The information collected thus will be disclosed to or collected directly by these plugins and may be used to improve the content and/or functionality of the services offered to you. Analytics companies may use mobile device IDs to track your usage of the Cheflab Platform;
                
                Other information you provide. With your permission, we may access your photos or contact list from your mobile device, Facebook Messenger account or email account to enable you to share content or promotions or invite your friends to connect with our Platform and/or Services, including through our friend referral program. 
                We may also use aggregate personal information for regulatory compliance, industry and market analysis, research, demographic profiling, marketing and advertising, and other business purposes, as long as the end-product does not uniquely identify you or any other user of the Platform and/or Services.
                1.2. Personal Information Generated and/or Automatically Collected during your use of the Platform and/or Services
                We may automatically collect certain information about the computer or devices (including mobile devices) you use to access the Services, and about your use of the Services, even if you use the Services without registering or logging in.
                Information about your device and its software. Information about your device and its software includes your IP address, browser type, internet service provider, device type/model/manufacturer, operating system, date and time stamp, and a unique ID that allows us to identify your browser, mobile device, or your Account (including, for example, a persistent device identifier or an Ad ID), and other similar information. We may also work with third-party partners to employ technologies, including statistical modeling tools, that permit us to recognize and contact you across multiple devices. We use this device and software information to diagnose and fix technology problems, serve you personalized advertising, personalize your experience, perform analytics/identify usage trends, and improve our products, Platform and/or Services.
                Information about the way you access and use our Services. Information about the way you access and use our Services includes the site from which you came and the site to which you are going when you leave. In addition, we track the pages you visit on the Platform, the links you click on the Platform, whether you open emails or click the links contained in emails that we send, other actions you take on the Services, and whether you access the Services from multiple devices. We may use third-party analytics tools to record your mouse movements, scrolling, and click activity on our Services to understand how our users engage with our Services and to monitor and improve our online offerings. We may also use the information about the way you access and use our Services to determine products and services that may be of interest to you, to improve our products and Services, to evaluate the success of our advertising and marketing campaigns, and to send you marketing communications.
                Analytics information. We may collect analytics data or use third-party analytics tools such as Google Analytics to help us measure traffic and usage trends and the demographics of our users in order to improve our Platform and/or Services. You can learn more about Google s practices at http://www.google.com/policies/privacy/partners.
                Location Information. In some cases, you provide your location information to us directly (e.g. when you provide us with a delivery address). In other cases, we may collect your location through GPS, WiFi, wireless network triangulation or other methods, or we may otherwise infer your location based on other information we collect. (For example, we can approximate your location by your IP Address.) We use location information to customize content on our Platform and/or Services (e.g., show you the Merchants that will deliver to your location and show you relevant Perks), facilitate order and delivery Services, detect and prevent fraud, and measure traffic and analytics on the Platform and/or Services. If you have previously opted into Cheflab’s collection and use of location-based information through our mobile application, we may collect and store the precise location of your device when the app is running in the foreground or background of your device. You may opt-out by adjusting the settings on your mobile device. We also use the Google Maps API to gather information about your location. Google uses various technologies to determine your location, including IP address, GPS and other sensors that may, for example, provide Google with information on nearby devices, WiFi access points and cell towers.
                We typically collect the foregoing generated and/or automatically collected information through a variety of tracking technologies, including cookies, Flash objects, web beacons, embedded scripts, mobile SDKs, location-identifying technologies, and similar technology (collectively, “tracking technologies”), and we may use third-party partners or services to assist with this effort. Information we collect automatically about you or your device may be combined with other personal information we collect directly. 
                We, or the third-party partners we use, may use the data collected automatically through tracking technologies to: (a) remember information so that you will not have to re-enter it during your visit or the next time you visit the Platform and/or Services; (b) provide custom, personalized content and information; (c) identify and contact you across multiple devices; (d) provide and monitor the effectiveness of our Platform and/or Services; (e) perform analytics and detect usage patterns on our Platform and/or Services; (f) diagnose or fix technology problems; (g) detect or prevent fraud or other harmful activities, and (h) otherwise plan for and enhance our Platform and/or Services and for other internal purposes.
                1.3. Data from other sources
                Information from other Account holders. We may receive personal information about you from Cheflab Account holders. For example, when using the group order feature, a Cheflab Account holder can invite other users (“Group Order Users”) to add to an order using the Cheflab Account holder’s own account. As a result, the Cheflab Account holder will provide information on the Group Order Users to Cheflab.
                Information we receive from third-party sites you connect to our Services. We may receive personal information about you from third parties and combine that with information we collect through our Platform and Services. For example, we may obtain information when you login through a third-party social network or authentication service, such as Facebook or Google. These services will authenticate your identity and provide you the option to share certain personal information with us, which could include your name, email address, address book and contacts, or other information. Similarly, when you interact with us through a social media site or third-party service, such as when you like, follow or share Cheflab content on Facebook, Twitter, or other sites, we may receive information that you permit the social network to share with third parties. The data we receive from these third-party sites is dependent upon that third party’s policies and your privacy settings on that third-party site.
                Information we receive from affiliates or third parties. From time to time, we may receive information about you from third parties, including without limitation: our Merchant partners, other Cheflab entities and affiliates, co-marketing partners and service providers, as well as in connection with our enterprise programs. For example, if your company, university, or organization participates in one of our enterprise programs, we may receive your information from that participating organization for the purpose of setting up your Accounts or for billing purposes. We may receive additional information about you, such as fraud detection information, from third-party partners and combine it with other information that we have about you. We use this information from affiliates or third parties to create your Accounts, to contact you, to send you advertising or promotional materials or to personalize our Platform and Services, to protect against bot attacks and account takeovers, and to better understand the demographics of our users.
                We do not control, supervise, or respond to how third parties providing your information process your personal information. Therefore, any information request regarding the disclosure of your personal information to us should be directed to such third parties.
                2. How We Use Your Personal Information
                In addition to the uses described above, we may collect and use personal information to:
                2.1. Provide, maintain, improve and develop the Platform and Services. We may use the personal information to provide, maintain, improve and develop the Platform and Services. For example, we:
                •	Enable you to create Accounts or otherwise access and use the Platform and Services (e.g., remember information so that you will not have to re-enter it during your visit or the next time you visit),
                •	Fulfill your requests and process payments (e.g., to allow you to order food from Chefs and have it delivered to you, or to provide you with information that you request),
                •	Provide custom, personalized content and information (e.g., “most popular near you” and “since you enjoy” features),
                •	Perform analytics, detect activity patterns on our Platform and Services, and otherwise research usage, and
                •	Test and develop new features and functionality and otherwise enhance the Platform and Services.
                2.2. Maintain the safety, stability and security of our Platform and Services. We may use the personal information to maintain the safety and security of our Platform and Services. For example, we:
                •	Detect or prevent fraud, abuse, or other harmful activities,
                •	Diagnose or fix technology problems,
                •	Conduct security investigations and risk assessments, and
                •	Improve and enforce our security measures.
                2.3. Communications with you to provide support and other important messages. We may use personal information to communicate important messages to you and/or to provide you with support. For example, we might send you service-related emails or messages (e.g., user Account verification, changes or updates to features of the Platform or Services, technical and security notices) and other communications from or about Cheflab.
                2.4. Provide, personalize, measure and improve our advertising and marketing. We may use personal information to provide, personalize, measure, and improve our advertising and marketing. For example, we may:
                •	Administer rewards, surveys, sweepstakes, contests, or other promotional activities or events sponsored or managed by Cheflab or its third-party partners,
                •	Inform you of products, programs, services, and promotions that we believe may be of interest to you, including, without limitation, through emails and push notifications,
                •	Permit you to refer us to your friends so that we may send them a promotional offer through the Platform or Services. If you wish to use this feature, you may be required to provide us with, and we may use, your friend s name, email address, and other information you share with us. By using this functionality, you affirm that you are entitled to use and provide us with your friend s name and email address for this purpose. We will use that information to send an email inviting the friend to visit the Platform and for any other purposes disclosed at the time of your participation in the program,
                •	Determine the effectiveness of our Platform, Services and our promotional campaigns, and
                •	Identify and contact you across multiple devices.
                2.5. Legal and regulatory requirements and proceedings. We may use the personal information in connection with legal and regulatory proceedings and requirements. For example, we may need the personal information to enforce our corporate reporting obligations, or to comply with applicable laws.
                2.6. Enforce our rights. When you access or use our Platform or Services, you are bound by our Terms of Use and this Privacy Policy. To ensure you comply with them, we may use your personal information to monitor, investigate, prevent, and/or mitigate violations of our Terms of Use as well as enforce our agreements with third parties and business partners.
                2.7. Other purposes disclosed at the time of collection. From time to time, we may use personal information for a specific purpose not contemplated by this Privacy Policy. In such an event, we will specifically disclose that use to you.
                3. Our Sharing and Disclosure of Personal Information
                We disclose personal information to the following types of third parties:
                3.1. Merchant Sharing. We disclose personal information to the Chefs/Restaurants you order from as needed to fulfill your orders (including communicating with you about the status of your order or cancelled items). If you make a purchase from one of our associate partner that offers loyalty or rewards programs through our Platform and Services, we may disclose your personal information to the same as needed to facilitate your participation in the loyalty or rewards programs, including to track points and redemptions. In some cases, you may also affirmatively opt in on the Platform or Services to share your information directly with the Merchant.
                3.2. Other Third Parties necessary to complete your order or to enable your use of the Platform and Services. In addition to Chefs you order from, we disclose personal information to other third parties as needed to fulfill your orders, including, without limitation, delivery providers and payment processors. Our third-party payment processors,  will use and process your payment information in accordance with their own separate privacy policy. 
                3.3. Information provided to third parties in connection with our enterprise customers. If your company, university, or organization participates in one of our enterprise programs, we may share some of your information with that organization, including your name, student ID number, contact details, order history, and other information as required to enable use by you and the organization of such Services. If you are a campus user, we also share your information with food providers that operate restaurants and other food ordering and delivery services on your campus to facilitate your use of the Services and for such providers to send you personalized communications and marketing.
                3.4. Service providers and contractors. We disclose personal information to third parties that provide services for us or on our behalf, such as website hosting, data analysis, infrastructure provisioning, IT services, customer service, email delivery services, fraud detection, security monitoring, advertising and marketing, and other similar services.
                3.5. Analytics providers. We share personal information with third-party analytics providers to better understand the demographics of our users and visitors, and to personalize, enhance and improve our Platform and Services.
                3.6. Advertising, Marketing, and Promotions providers. We share personal information with third parties in connection with co-marketing activities, the development of customized and targeted marketing campaigns, to launch promotions and for other similar advertising efforts. For example:
                •	Promotional partners. We disclose personal information to third-party sponsors of promotions to provide contests, sweepstakes, joint promotional activities, or co-branded services when such disclosure is necessary to fulfil your request or application. You should carefully review the rules and/or terms of each promotion in which you participate, as the promotion may contain additional important information about our, a sponsor s, and/or other third parties  use of your personal information. To the extent that the rules or terms of those promotions concerning the treatment of your personal information conflict with this Privacy Policy, the rules of those promotions will control.
                •	Ad networks and advertising partners. We work with third-party Ad Networks and Advertising Partners to deliver advertising and personalized content to you on our Platform and Services, on other sites and services you may use, and across other devices and advertising channels you may use. These parties may collect information directly from your browser or device when you visit the Platform through cookies or other tracking technologies. This collected information is used to provide and inform targeted advertising, as well as to provide advertising-related services such as reporting, attribution, analytics and market research. 
                •	Social networks. We disclose personal information, such as a unique identifier, hashed email address, or information automatically collected through tracking technologies, to social networks for the purpose of displaying personalized advertising and content on those social networks.
                •	Select restaurants. We may disclose personal information to select restaurants from where you have placed order for Dine-In services through the Platform as well as their affiliates and third-party service providers. These restaurants, and their affiliates, may use your information as permitted by their own privacy policies, which could include sending you marketing communications and other promotional content.
                3.7. Affiliate Sharing. We share your personal information with other companies owned or controlled by Chotu18 Services Pvt.Ltd.., and other companies owned by or under common ownership as Chotu18 Services Pvt.Ltd., which also includes our subsidiaries (i.e., any organization we own or control) or our ultimate holding company (i.e., any organization that owns or controls us) and any subsidiaries it owns, for operational or business purposes or as otherwise described in this Privacy Policy.
                3.8. Public. We make available through the Platform and Services certain features which may enable you to post information and materials, for example, Ratings and Reviews, photo uploads, and chat functionality. Please note that any information you provide in connection with such Services may be available to site visitors and to the general public. We urge you to exercise discretion and caution when deciding to disclose information and/or materials in these public or interactive areas on the Services, and in no event should you disclose your personal information in these public or interactive areas on the Platform or Services.
                3.9. Business Transaction or Reorganization. We may take part in or be involved with a corporate business transaction, such as a merger, acquisition, joint venture, or financing or sale of all or a portion of company assets. We may disclose personal information to a third party during negotiation of, in connection with, or as an asset in such a corporate business transaction. Personal information may also be disclosed in the event of insolvency, bankruptcy, or receivership.
                3.10. Legal Obligations and Rights. We may disclose personal information to third parties, such as legal advisors and law enforcement, as required by law or if we reasonably believe that such action is necessary to (a) comply with the law and the reasonable requests of law enforcement; (b) enforce our Terms of Use or to protect the security or integrity of our Platform and Services; (c) detect, suppress, or prevent fraud or reduce credit risk and collect debts owed to us; and/or (d) exercise or protect the rights, property, or personal safety of Cheflab, our visitors, or others.
                3.11. Consent. We may disclose personal information about you to other third parties with your consent.
                4. Control Over Your Personal Information
                Profile Settings. You may update your profile information in the “Your Account” section of the Services.
                Manage Your Data. You may submit a request to get a copy of your Personal Information, to understand what we collect and how we share your Personal Information, or to delete your Personal Information. In certain circumstances, we may decline such a request, such as when we are unable to verify your identity, or when we are unable to delete your information for legal or regulatory reasons..
                Access to your Device Information and Push Notifications. You may control access to your device information or opt out of push notifications through the “Settings” app on your device. For instance, you can withdraw permission for the app to access your location data through your device settings, though we may continue to approximate your location based on your IP address or through other means.
                How to control your communications preferences. You can stop receiving promotional email communications by clicking on the “unsubscribe link” provided in such communications. You may not opt out of service-related communications (e.g., Account verification, transactional communications, changes/updates to features of the services, technical and security notices). You may also unsubscribe from receiving certain order-related text (SMS) or multimedia (MMS) messages by replying "STOP" to the number sending the message. 
                
                
                5. How We Store and Protect Your Information
                Data storage and transfer. If you create an Account on the Platform, by using and/or accessing the Platform or Services, you consent to the collection, transfer, storage, and processing of your information.
                Keeping your information safe. We care about the security of your information and employ physical, administrative, and technological safeguards designed to preserve the integrity and security of all information collected through our Platform and Services. However, no security system is impenetrable and we cannot guarantee the security of our systems. Please recognize that protecting your personal information is also your responsibility. Accordingly, we strongly recommend that you change your passwords often, use a combination of letters and numbers, make sure you use a secure browser, and otherwise take precautions when communicating your personal information on the internet. If you know or have reason to believe that your Account credentials have been lost, stolen, misappropriated, or otherwise compromised or in case of any actual or suspected unauthorized use of your Account, please contact us following the instructions in the Contact Us section below.
                6. Children’s Personal Information
                Our websites and online Services are not directed to, and we do not intend to, or knowingly, collect or solicit personal information from children under the age of 18. In the event that we learn that we have inadvertently collected personal information from a child under age 18, we will delete that information as quickly as possible. If you have a basis for believing that we have any information from a child under 18, please contact us at support@cheflab.in 
                7. Third-Party Websites
                Our websites and online Services may include links to third-party websites, plug-ins and applications. Except where we post, link to, or expressly adopt or refer to this Privacy Policy, this Privacy Policy does not apply to, and we are not responsible for, any personal information practices of third-party websites and online services or the practices of other third parties. To learn about the personal information practices of third parties, please visit their respective privacy notices.
                8. Updates to This Privacy Policy
                We may update this Privacy Policy from time to time. When we make changes to this Privacy Policy, we will change the "Effective" date at the beginning of this Privacy Policy. In addition to posting the updated Privacy Policy and “Effective” date, we may elect to provide additional notice to you of the updated Privacy Policy, such as by sending an email to you or providing a notice through the Platform and/or Services. All changes shall be effective from the date of publication unless otherwise provided. If you do not cancel your Account before the date the revised Privacy Policy becomes effective, your continued access to or use of the Platform and/or Services will be subject to the revised Privacy Policy.
                9. Contact Us
                If you have any questions or requests in connection with this Privacy Policy or other privacy-related matters, please send an email to support@cheflab.in
                Alternatively, inquiries may be addressed to:
                Mr. Grishu Mutneja
                Email : support@cheflab.in
                Please note that email communications will not necessarily be secure; accordingly, please do not include credit card information and/or other sensitive personal information in your email correspondence with us.
                
                10.Jurisdiction
                If you choose to visit the website, your visit and any dispute over privacy is subject to this Policy and the website s terms of use. In addition to the foregoing, any disputes arising under this Policy shall be governed by the laws of India and place of jurisdiction will be Indore ( M.P ) only.',
                'vendor_privacy_policy'=>'Banner 1',
                'deliveryboy_privacy_policy'=>'Banner 1',
                'terms_conditions_vendor'=>'Banner 1',
                'terms_conditions_user'=>'1',
                'terms_conditions_deliverboy'=>'1',
                'refund_cancellation_user'=>'30',
                'refund_cancellation_vendor'=>'2',
                'refund_cancellation_deliveryboy'=>'Cheflab',
                ],

                
            ]
            
        
        );
    }
}
