<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CuisinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('cuisines')->insert(
            [
                [
                'name'=>'African',
                'cuisinesImage'=>'cuisines-1.jpg',
                'position'=>'1',
                'is_active'=>'1'
                ],
                [
                'name'=>'American',
                'cuisinesImage'=>'cuisines-2.jpg',
                'position'=>'2',
                'is_active'=>'1'
                ],
                [
                'name'=>'Andhra',
                'cuisinesImage'=>'cuisines-3.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Arabian',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'4',
                'is_active'=>'1'
                ],
                [
                'name'=>'Bengali',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'5',
                'is_active'=>'1'
                ],
                [
                'name'=>'Cafe',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Chettinad',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Chinese',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Coastal',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],      
                [
                'name'=>'Continental',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ], 
                [
                'name'=>'Desserts',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'European',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Fast Food',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'French',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Goan',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Greek',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Gujarati',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Healthy Food',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Home Food',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Hyderabadi',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Indian',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Italian',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Italian-American',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Jain',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Japanese',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Kerala',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Keto',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Konkan',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Korean',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Lebanese',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Lucknowi',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Maharashtrian',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Malaysian',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Mangalorean',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Mediterranean',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Mexican',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Middle Eastern',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Mughlai',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Naga',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Nepalese',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'North Eastern',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'North Indian',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Oriental',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Pan-Asian',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Parsi',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Persian',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Portuguese',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Rajasthani',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'South Indian',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Thai',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Tibetan',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ],
                [
                'name'=>'Turkish',
                'cuisinesImage'=>'cuisines-4.jpg',
                'position'=>'3',
                'is_active'=>'1'
                ]
            ]
            
        
        );
    }
}
